version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
      - pip install --upgrade aws-sam-cli
      - pip show aws-sam-cli  # Verificar la instalación de SAM CLI

  pre_build:
    commands:

  build:
    commands:
      - sam build --debug  # Añadir --debug para obtener más detalles

  post_build:
    commands:
      - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket prueba22222 --debug
      - aws cloudformation deploy --template-file packaged.yaml --stack-name stack-prueba --capabilities CAPABILITY_NAMED_IAM --region us-east-2 --disable-rollback

artifacts:
  files:
    - template.yaml