version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
      - pip install --upgrade aws-sam-cli
      - pip show aws-sam-cli

  pre_build:
    commands: []

  build:
    commands:
      - sam build --debug 2>&1 | tee build.log

  post_build:
    commands:
      - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket lambda-prueba-bucket --debug 2>&1 | tee package.log
      - aws cloudformation deploy --template-file packaged.yaml --stack-name stack-prueba --capabilities CAPABILITY_NAMED_IAM --region us-east-2 --debug 2>&1 | tee deploy.log

artifacts:
  files:
    - build.log
    - package.log
    - deploy.log
