version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
      - pip install --upgrade aws-sam-cli
      - pip show aws-sam-cli  # Verificar la instalación de SAM CLI

  pre_build:
    commands:

  build:
    commands:
      - sam build --debug  # Añadir --debug para obtener más detalles

  post_build:
    commands:
      - aws cloudformation package --template-file template.yml --output-template-file template-out.yml --s3-bucket dso-test-bucket

artifacts:
  files:
    - template.yaml
    - template-out.yml