AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Resources:

  # Lambda Function and API Gateway
  LambdaPrueba:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: back/lambdaprueba/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        LambdaPrueba:
          Type: Api
          Properties:
            Path: /user/prueba
            Method: get

Outputs:
  # Output for API Gateway URL
  ApiGatewayUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
