Transform: AWS::Serverless-2016-10-31
Description: Funciones para deploy CI/CD Front y Back

Globals:
  Function:
    Timeout: 3

Resources:

  # Lambda Function and API Gateway
  LambdaPrueba:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: back/lambdaprueba/
      Architectures:
        - x86_64
      Events:
        LambdaPrueba:
          Type: Api
          Properties:
            Path: /test
            Method: get
